# Download docker images
# Load docker images
name: run-integration-test
description: "Run integration test"
inputs:
  integration_test:
    description: "M_INTEG_DIR value"
    required: true
  serverVersion:
    description: "Override server version used in the test file"
    required: false
  serverImage:
    description: "Override server image used in the test file"
    required: false

runs:
  using: "composite"
  steps:
    - name: Free diskspace by removing unused packages
      shell: bash
      run: |
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
        cache: true
    - name: Create Kind Cluster
      uses: helm/kind-action@v1.4.0
      with:
        version: v0.17.0
        node_image: kindest/node:v1.25.3
        cluster_name: kind
        config: tests/testdata/kind/kind_config_6_workers.yaml
    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: 3.10.2
      id: install_helm
    - name: Download cass-operator image
      uses: actions/download-artifact@v3
      with:
        name: cass-operator
        path: /tmp
    - name: Download system-logger image
      uses: actions/download-artifact@v3
      with:
        name: system-logger
        path: /tmp
    - name: Load Docker images
      shell: bash
      run: |
        docker load --input /tmp/k8ssandra-cass-operator.tar
        docker load --input /tmp/k8ssandra-system-logger.tar
    - name: Load image on the nodes of the cluster
      shell: bash
      run: |
        kind load docker-image --name=kind k8ssandra/cass-operator:latest
        kind load docker-image --name=kind k8ssandra/system-logger:latest
    - name: Run integration test ( ${{ inputs.integration_test }} )
      shell: bash
      run: |
        IMG=k8ssandra/cass-operator:latest make integ-test
