# Download docker images
# Load docker images
name: run-integration-test
description: "Run integration test"
inputs:
  integration_test:
    description: "M_INTEG_DIR value"
    required: true
  serverVersion:
    description: "Override server version used in the test file"
    required: false
  serverImage:
    description: "Override server image used in the test file"
    required: false

runs:
  using: "composite"
  steps:
    - name: Free diskspace by removing unused packages
      shell: bash
      run: |
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
        cache: true
    # The runners already have the latest versions of tools, no need to reinstall them
    - name: Link tools
      shell: bash
      run: |
        mkdir bin
        ln -s /usr/local/bin/kustomize bin/kustomize
    - name: Create kind cluster
      shell: bash
      run: |
        hack/cluster.sh
    - name: Download cass-operator image
      uses: actions/download-artifact@v3
      with:
        name: cass-operator
        path: /tmp
    - name: Download system-logger image
      uses: actions/download-artifact@v3
      with:
        name: system-logger
        path: /tmp
    - name: Load Docker images
      shell: bash
      run: |
        docker load --input /tmp/k8ssandra-cass-operator.tar
        docker load --input /tmp/k8ssandra-system-logger.tar
    - name: Set version value
      id: vars
      shell: bash
      run: |
        echo "version=$(make version)" >> $GITHUB_OUTPUT
    - name: Load image on the nodes of the cluster
      shell: bash
      run: |
        kind load docker-image --name=kind k8ssandra/cass-operator:v${{ steps.vars.outputs.version }}
        kind load docker-image --name=kind k8ssandra/system-logger:v${{ steps.vars.outputs.version }}
    - name: Run integration test ( ${{ inputs.integration_test }} )
      shell: bash
      run: |
        IMG=k8ssandra/cass-operator:v${{ steps.vars.outputs.version }} LOG_IMG=k8ssandra/system-logger:v${{ steps.vars.outputs.version }} make integ-test
