# Set WATCH_NAMESPACE to "" in the deployment to provide cluster-wide install
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- patch: |-
    - op: remove
      path: /spec/template/spec/containers/0/env/0/valueFrom
    - op: add
      path: /spec/template/spec/containers/0/env/0/value
      value: ""
  target:
    group: apps
    kind: Deployment
    name: controller-manager
    version: v1
- patch: |-
    - op: replace
      path: /metadata/name
      value: cass-operator-manager-crrole
    - op: replace
      path: /kind
      value: ClusterRole
  target:
    group: rbac.authorization.k8s.io
    kind: Role
    name: manager-role
    version: v1
- patch: |-
    - op: replace
      path: /roleRef/kind
      value: ClusterRole
    - op: replace
      path: /roleRef/name
      value: cass-operator-manager-crrole
    - op: replace
      path: /subjects/0/name
      value: cass-operator-controller-manager
    - op: add
      path: /subjects/0/namespace
      value: cass-operator
    - op: replace
      path: /kind
      value: ClusterRoleBinding
  target:
    group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: manager-rolebinding
    version: v1
