apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cassandra-nonroot
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - nonroot
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cassandra-nonroot-rolebinding
subjects:
  - kind: ServiceAccount
    name: cassandra-default-sa
roleRef:
  kind: Role
  name: cassandra-nonroot
  apiGroup: rbac.authorization.k8s.io
