apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Auto Pilot
    categories: Database,Big Data,OpenShift Optional
    certified: "true"
    description: |
      Simple provisioning, turn-key operations, and automated remediation of Apache Cassandra clusters
    repository: https://github.com/k8ssandra/cass-operator
    support: DataStax
  name: cass-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CassandraDatacenter is the Schema for the cassandradatacenters
        API
      displayName: Cassandra Datacenter
      kind: CassandraDatacenter
      name: cassandradatacenters.cassandra.datastax.com
      version: v1beta1
  description: ${CSV_DESCRIPTION}
  displayName: DataStax Kubernetes Operator for Apache Cassandra
  icon:
  - base64data: |
      iVBORw0KGgoAAAANSUhEUgAAAeAAAAHgCAYAAAB91L6VAAAACXBIWXMAACxLAAAsSwGlPZapAAAA
      AXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAABVeSURBVHgB7d1NbF3lmcDxlyo77O1gs8VhS8gy
      NFlUo3ZgmUCyqIakiTSVaApVO1OgRJ0REqWqNFVDKaOpRChIrZSUdEcQHc3GjlkmYRs7s3WYbcLa
      4+e6FwWGjzg+9z73Oef3k67sJF2E+Pb+z/tx3nPfgQPf2mwAwDRtfqMBAFMnwACQQIABIIEAA0AC
      AQaABAIMAAkEGAASCDAAJBBgAEggwACQQIABIIEAA0ACAQaABAIMAAkEGAASCDAAJBBgAEggwACQ
      QIABIIEAA0ACAQaABAIMAAkEGAASCDAAJBBgAEggwACQQIABIIEAA0ACAQaABAIMAAkEGAASCDAA
      JBBgAEggwACQQIABIIEAA0ACAQaABAIMAAkEGAASCDAAJBBgAEggwACQQIABIIEAA0ACAQaABAIM
      AAkEGAASCDAAJBBgAEggwACQQIABIIEAA0ACAQaABAIMAAkEGAASCDAAJBBgAEggwACQQIABIIEA
      A0ACAQaABAIMAAkEGAASCDAAJBBgAEggwACQQIABIIEAA0ACAQaABAIMAAkEGAASCDAAJBBgAEgg
      wACQQIABIIEAA0ACAQaABAIMAAkEGAASCDAAJBBgAEggwACQQIABIIEAA0ACAQaABAIMAAkEGAAS
      CDAAJBBgAEggwACQQIABIIEAA0ACAQaABAIMAAkEGAASCDAAJBBgAEggwACQQIABIIEAA0ACAQaA
      BAIMAAkEGAASCDAAJBBgAEggwACQQIABIIEAA0ACAQaABAIMAAkEGAASCDAAJBBgAEggwACQQIAB
      IIEAA0ACAQaABAIMAAkEGAASCDAAJBBgAEggwACQQIABIIEAA0ACAQaABAIMAAkEGAASCDAAJBBg
      AEggwACQQIABIIEAA0ACAQaABAIMAAkEGAASCDAAJBBgAEggwACQQIABIIEAA0ACAQaABAIMAAkE
      GAASCDAAJBBgAEggwACQQIABIIEAA0ACAQaABAIMAAkEGAASCDAAJBBgAEggwACQQIABIIEAA0AC
      AQaABAIMAAkEGAASCDAAJBBgAEiwp9Gp1dX/buzMxsbHn35/8+bN0dfbt2+3W7dub/3Zza3vPxl9
      H38Wvz/+PYZjcfGBNjc315aWlkbfLy4utPn5udHvLSwsjP43c3P3j36PbmxubrZvfvPvG5MjwKSL
      D9Qv+v6rRJDX12+Mgnz9+npbW7sxCnR8pbYI6cGD32wPP/xQ27t3aSu6DwkrvSTAlBQfyI8++sjo
      +4MHH/vMn41jfOXKR1vfr7erVz9qzK4IboT20KHHRuG924swqE6A6Z29ex8avcZhHo+Wl5dXBXmG
      xAVURPfxx79jhMsgCTC9Nx4tj0fMEeRr1z4aBXl5+bL15CmK0e4TT/zD1us7o4skGLL7Dhz41maj
      MzZh1bOysjqK8aVLHzQmI8J77NiT7amnDhvtFmET1sRtCnDHBLiuGBlHjCPEpqm7E9PMzz77zGjn
      MnUI8MRtmoKGv4mRWUyNxis2cl24cNGoeBcWFh5oZ848/+nUP/BZDuKALxDrky+99NP27rt/HAWZ
      nYlR7x/+8Hvxha8gwPAVYtpUiHfm5Mnj7dVXX7bWC19DgOEuCPHdeeml59upU0834OsJMOzAOMS/
      /OXLozVOtsUu59df//XWxcm3G3B3BBjuQRzycfHin7ZGe8cb2yNf672wMwIMu3Dy5NOjaekhj4af
      e+4Ho01XwM4IMOxSTEu//fbv27FjR9rQxIaro0cPN2DnBBg6EI/Fi8MmhjQlHU8psuEK7p0AQ4di
      Sjruf+37lHT898VGNODeCTB0LA7xiB3BfY5wjPQdLQm7I8AwARGnvkY4LjDcCw27J8AwIX2NcJxy
      BeyeAMME9S3CMfI19QzdEGCYsD5FODaZAd0QYJiCcYTjdqWqjH6hWwIMUxLxqnzrjo1X0C0BhimK
      85Kfe+6ZVk3sfHbWM3RLgGHKjh49MnqYQyXxdwa6JcCQ4MyZn5balGX0C90TYEgQm7HOnHm+VRDx
      tfkKuifAkCTCVuEJSjZfwWQIMCSK+2pnfSo6NmAB3RNgSBRT0T/60Q/arIqLg717lxrQPQGGZLEj
      elY3OYkvTI4AwwyIx/vNIrufYXL2NAbj9u3b7fz5i20aPr9rdvzrubn7R9OudtV+VoQuRsIrK6tt
      ljz8cH9GwPH+X1u70TY2bo5+Pf4KWQR4QG7dut3OnXunzYr5+bnRGuPCwsIoyIuL2+uNsemn8pnJ
      9ypOyJq1AFcfAV+9eq0tL3+49e96eSu4HzeYJQJMmrggiFeMSj4vgry09FDbv/+RUZSHMBUa/82H
      Dj22FYzZiHDl3c8R3jfffGfr60cNZpUAM5NiejBe4xFhjJb37XtkFKiIcoya+yiOfJyVAFedhTh3
      7u1RfGHWCTAlxEg5YjwOchwOEa++jYzjvydeszByqzgCFl8qsQuaki5d+qCdPv3j9uST3x193yez
      siO62izDhQsXxZdSBJjSYpr6lVd+NQrxrG1gulcxAp6F6d8HH6wT4Js3b7azZ99oUIkA0wsR4hde
      +PkoxvFhXN2xY4dbtkprwEa+VCTA9Mr21PRPvnBndSWz8PzdKlPQccHVt2UIhkGA6Z0YDZ848U9b
      o6K3W1Ux+szeYDY/f3+rYFZ2jcNOCTC9FYeOVI5w3HKVqcoUtABTlQDTa5Uj7Dm8d6f6cgPDJcD0
      XkS44hph5jR0ldFvnO8cL6hIgBmEuEWl4kgpTv3KECePVeCBClQmwAxCjJJefPHn5UZLjz66r/Hl
      jH6pTIAZjBgtVbtfdFYO5QC6J8AMShxXWG0q+tChAw3oHwFmcM6e/V2rJB7HyBczO0BlAszgxJOG
      Kj0n9uDB6d8PHE+fqkCAqUyAGaRK9wYvLi5MPTRVNjdl/NtAVwSYQYoRcKUdtBWfzTst/m2oSoAZ
      rPPnL7YqMiKzsfFxqyD7yE64VwLMYL3//l9bFfv3ux/4yziyk6oEmMGK+4KrbMZaWpr+CLjKc5Vn
      4clRcC8EmEG7cuVaqyBjs1GlYx5feumnNmNRjgAzaJVuR1pcfKBNU5VbkUJcoJw69XSDSgSYQau0
      G3raG7GqTEGPHT16ZCvCxxtUIcAMXpWjKRcWFto0VdkFfaeTJ58WYcoQYAbv+vX1VkFMs07T+nrN
      B91HhN999482ZjHzBJjBq7IOPO0p6NiEVfVxf3Gx8vrrvx694jalhYXprp/D3djTYOCqjPQydvnG
      9HzlkWT83cd//9hUFj/r8YXFLG0yG0/3j9fd42vFJQB2RoAZvPEH8qzfxjLtKegQ0/N9mcqdn5/7
      TJAriAugeG+ura2PghxfK+3c56sJMLTtCFd47F/cijTNkVG1Zyf3zXjZ4fMXDRHhiPHy8qogFybA
      0LZDUyHA26P06QV4ZWW1MXvGI/m49Sqm0uPnFDH286pFgKHVOXQipqGnOSqN6c8YcU/7EBDuXkyt
      x0azeI2PV43Hbd68aQ151tkFDa3Sucf3t2lbXr7cqCEu0CLEFy/+abQD3K1Ys02AocUI+JNWQcZG
      MdOaNUV8I8K//e2/uw1rRgkwtFpP/pm2Ssd18v/FoyxjRBwPrBDi2SLA0FqZ9bJY78vw3nsfNGqL
      qenxwSTMBgGGQrLuVTYN3Q+xRhwjYedlzwYBhlbr2bcZYhra/ab9Eedlv/XWf5qSTibAUEjWFHSI
      W1voj4cfXrJBK5kAw99UOHs34zaksfHpS/THgw8uinAiAQbu2tmzbzT6RYTzCDBw16wF95MI5xBg
      YEesBfdTRPjVV1+e+aeC9YkAAzsSI+Dz5y82+ic2ZsUOaaZDgIEdO3funTKnh7Ezx44dGb2YPAEG
      diyOpnzhhZ87orKnvve9f7QePAUCDNyTeCyiXdH9ND8/Pzoxi8kSYOCeXbr0gU1ZPRVPU/I4w8kS
      YGBXYj1YhPvnvvvuaz/72b80JkeAgV0T4X6KW5M8PWlyBBj+ZnHRppPdEOF+ig1ZTIYAQyG3b3/S
      ZllE2O7ofolHGB469FijewIMrZU5/efWrdkPWzw7+MSJ77tPuCdiLfippw43uifA0HIf87cTVUaW
      8XzlI0e+a0q6J+yIngwBhi1VDh2oMAK+U0xJP/nkd0e3K1FXjIIPHjQN3TUBBiYqRsOvvPKrdvr0
      jz1JqbAnnvh2o1sCDC1GwAutgsrrqhHfiHC8jIjriX0SpqG7tacBZW5B2tj4uFU3fqZwTE/HB/rR
      o4fb3r1LjdkW09D79z9iFqNDAgxt+zFsTFdMTccrRsNxq0usMcbtLkZZs2vfPj+bLgkwtDq3IfX1
      1p4I8YULF0ev2JG+tPTQKMT79+8bzU5UWSLou/iZxP9X3OfdDQGGLXv3PtQq6MMU9NeJnd53TlOH
      cZTjwz9+VvHriPL21+3lgxhFM3kxDb28vNrYPQFm8OJDvcIIeMijjnGUQxz0UUFcHMzN3T+6UIg1
      7rhwiHhVHs3HOnBMQwtwNwSYwasy+l1bW2/UERcN8YpZizs3LsU07qlTx8uudTszvTtuQ2LwqgR4
      1s+B5u6Mb8eKe6MrrunHUgDdEGAGLzb6VHD9uhFwn8Tu79Onf1IuwrHWXmXT4qwTYAavyhW9hxv0
      T+z+Pn683oMrTEN3Q4AZtJh+rrJ7dgg7oIcoNtfFIxyriI1YVZZtZp0AM2iVTmBaW7vR6Kf42Z4/
      f7FVYQq6GwLMoD3xxHdaBTFF6fCDfhvf81yBg1G6IcAMVhzgUOVWkFgrpN/iAqvKOctGwN0QYAar
      yu7ncOWKA/CHYHn5cqtgcfHvGrsnwAxWlennsL5u/XcIVlY+bBUYAXdDgBmkStPPwQh4GKosNQhw
      NwSYQYqjAKuIIyhtwBoOt5sNhwAzODH6rTT97PajYXHgynAIMINTafQbquyMBXZGgBmUgwcfKzX6
      DQIM/STADEY8m/W5555plcT6r3uAoZ8EmME4depEmXOfx4x+ob8EmEE4evTI1utwq2Z5ebUxLI55
      HA4Bpvfift9qU88hdsMaAQ9L3F9b4VF/bovrhgDTa/Gs31dffblV5PCN4anymD8B7saeBj0Vu52f
      ffaZNj9f89SeS5c+aAxLpdPZ2D0BppdOnjzeTp16ulVl+nmYqtwit7Hxv43dE2B6JU65OnPm+fIj
      CdPPwxPv2Sq79J3W1Q0Bpjdip/PJk0+XnXK+U6WHs9ONSie0WQPuhgBTXkzbRXir3eP7Za5evebw
      jYGJi8cqszabm5vOJ++IAFNSnGp17NiT7fHHv92b8I5duvTXxnDETv1qt8kZAXdDgCkjort379Kn
      o4U+TDV/Xqyt2f08HPE+rnibnBFwNwSYmTUObrwOHXpsNFLoY3Tv9Oab1n6HIN7bp06dKHk6W5xP
      TjcEmJkQp/8sLS2NppPjMILt8NY4lKArRr/9FyPe/fv3taeeOlz2YnJt7X8a3RDgAYn/w8dmpUn6
      /L2rd55rOz5iLyIbf5f4sypH703DrI9+4xavvq23T1K8t8fv7/h3e/TRfb14r1+75ha5rgjwgMSH
      QbWH0Q9FhdFvvHeqPUuZbm3vgDYF3RVnQcMMsPZLBbH72Qas7ggwJIuRr7VfKnA8arcEGJI59Yoq
      VlY+bHRHgCHRuXNvO/WKEmL91wi4WwIMSWLjlbVfqnBEavcEGBLEZpbTp3/SoIr33/+vRrcEGBK8
      +aapZ+q4detWW15ebXRLgGHKLly4uPX6S4Mqlpc/9ACGCRBgmKJY9z179o0GVcTmq7fesldhEgQY
      piTia92XauLxmJZLJkOAYQrG8fVBRiVGv5MlwDBhsXb2wgv/Kr6UY/Q7WQIMEzS+3cgB9lRj9Dt5
      AgwTIr5UFvE1+p0sAYYJiDXfEye+L76UtLGx4ZS2KRBg6JgNV1QWh2788If/3Ji8PQ3oTDxW8LXX
      3tj6EHNoATW99tp/uHicEgGGjpw9+zsnXFFaPJ3Ls6mnR4Bhl2LKOW4zst5LZefPX7TuO2UCDLsQ
      5zqfO/eOKWdKe++97aUTpkuA4R6sr6+33/zmDQ8op7yI7y9+8avG9Akw7EDc2xuPErTWSx/Emq9p
      5zwCDHchwhtrZH/+819MN1OeC8nZIMDwFYSXvolDNl588d9sGpwBAgxfQHjpI5sGZ4sAwx2uXr02
      WhOzuYo+uXLl2uiADaPe2SLADF5Ed3n5w/b++x8YGdArLihnmwAzSOPorqxc3loT+7hBnwhvDQLM
      IMTZtisrq1tTcR+1a9c+MtKld8b7FuJ9vrZ2ozH7BJjeiQ+iWOuKDyHBpc/ifR6j3OXlVaPdggSY
      smJUux3bG6NX/DpOqDKlTB/deWF5/fqNdvnyqgvL4gSYmREfMOMPlJs3Px59H78Xr4hq/DoefBCv
      27c/8eFDr4wfARjv/fHFZbzvXVj2130HDnxrs9GZxcUHGnfPh0od8/NzbW7u/kZ3XEgO2qYRcMcE
      hb6KUIgFdOcbDQCYOgEGgAQCDAAJBBgAEggwACQQYABIIMAAkECAASCBAANAAgEGgAQCDAAJBBgA
      EggwACQQYABIIMAAkECAASCBAANAAgEGgAQCDAAJBBgAEggwACQQYABIIMAAkECAASCBAANAAgEG
      gAQCDAAJBBgAEggwACQQYABIIMAAkECAASCBAANAAgEGgAQCDAAJBBgAEggwACQQYABIIMAAkECA
      ASCBAANAAgEGgAQCDAAJBBgAEggwACQQYABIIMAAkECAASCBAANAAgEGgAQCDAAJBBgAEggwACQQ
      YABIIMAAkECAASCBAANAAgEGgAQCDAAJBBgAEggwACQQYABIIMAAkECAASCBAANAAgEGgAQCDAAJ
      BBgAEggwACQQYABIIMAAkECAASCBAANAAgEGgAQCDAAJBBgAEggwACQQYABIIMAAkECAASCBAANA
      AgEGgAQCDAAJBBgAEggwACQQYABIIMAAkECAASCBAANAAgEGgAQCDAAJBBgAEggwACQQYABIIMAA
      kECAASCBAANAAgEGgAQCDAAJBBgAEggwACQQYABIIMAAkECAASCBAANAAgEGgAQCDAAJBBgAEggw
      ACQQYABIIMAAkECAASCBAANAAgEGgAQCDAAJBBgAEggwACQQYABIIMAAkECAASCBAANAAgEGgAQC
      DAAJBBgAEggwACQQYABIIMAAkECAASCBAANAAgEGgAQCDAAJBBgAEggwACQQYABIIMAAkECAASCB
      AANAAgEGgAQCDAAJBBgAEggwACQQYABIIMAAkECAASCBAANAAgEGgAQCDAAJBBgAEggwACQQYABI
      IMAAkECAASCBAANAAgEGgAR7tl6bDQCYps3/A6g4mk/vaKbmAAAAAElFTkSuQmCC
    mediatype: image/png
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - k8ssandra
  - cass-operator
  - DataStax Enterprise
  - Apache Cassandra
  - DSE
  - C*
  - Cassandra
  links:
  - name: DataStax
    url: https://datastax.com
  - name: Operator GitHub Repo
    url: https://github.com/k8ssandra/cass-operator
  - name: Config Builder GitHub Repo
    url: https://github.com/datastax/cass-config-builder
  - name: Documentation [1]
    url: https://github.com/k8ssandra/cass-operator/tree/master/docs/user
  - name: Documentation [2]
    url: https://docs.datastax.com/en/cass-operator/doc/cass-operator/cassOperatorTOC.html
  maintainers:
  - email: cass-operator@datastax.com
    name: DataStax Operator Team
  maturity: stable
  provider:
    name: DataStax
  version: 0.0.0
