apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cass-operator
namePrefix: cass-operator-

resources:
  - ../../default

components:
  - ../../components/namespace
  - ../../components/webhook
