# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
- bases/cass-operator.clusterserviceversion.yaml
- ../deployments/default
- ../samples
- ../scorecard

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - ../../docs/developer/csv-description.md
  name: field-config

# [WEBHOOK] To enable webhooks, uncomment all the sections with [WEBHOOK] prefix.
# Do NOT uncomment sections with prefix [CERTMANAGER], as OLM does not support cert-manager.
# These patches remove the unnecessary "cert" volume and its manager container volumeMount.
patchesJson6902:
- target:
    group: operators.coreos.com
    version: v1alpha1
    kind: ClusterServiceVersion
    name: cass-operator.v0.0.0
  path: patches/spec-descriptors.yaml
- target:
    group: operators.coreos.com
    version: v1alpha1
    kind: ClusterServiceVersion
    name: cass-operator.v0.0.0
  path: patches/status-descriptors.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: controller-manager
    namespace: system
  patch: |-
    # Remove the manager container's "cert" volumeMount, since OLM will create and mount a set of certs.
    # Update the indices in this path if adding or removing containers/volumeMounts in the manager's Deployment.
    - op: remove
      path: /spec/template/spec/containers/0/volumeMounts/0
    # Remove the "cert" volume, since OLM will create and mount a set of certs.
    # Update the indices in this path if adding or removing volumes in the manager's Deployment.
    - op: remove
      path: /spec/template/spec/volumes/0

replacements:
  - path: patches/description-replacement.yaml
