apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
- behavior: merge
  files:
  - controller_manager_config.yaml
  name: manager-config

resources:
- ../../webhook
- ../../certmanager

configurations:
- kustomizeconfig.yaml
patches:
- path: patches/manager_webhook_patch.yaml
