name: Kind Integration Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
jobs:
  kind_integration_tests:
    strategy:
      matrix:
        integration_test:
        - smoke_test_oss
      # let other tests continue to run
      # even if one fails
      fail-fast: false
    name: ${{ matrix.integration_test }}
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      GOROOT: /usr/local/go1.16
      M_LOAD_TEST_IMAGES: true
      M_INTEG_DIR: ${{ matrix.integration_test }}
      M_K8S_FLAVOR: kind
    steps:
      - uses: actions/checkout@v2
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/checkout@v2
        if: github.event_name != 'pull_request'
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.3
      - name: Create Kind Cluster
        uses: helm/kind-action@v1.1.0
        with:
          image: kindest/node:v1.20.2
          cluster_name: kind
          config: tests/testdata/kind/kind_config_1_worker.yaml
      - name: Build and push operator to kind
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: k8s:reloadOperator
      - name: Run integration test ( ${{ matrix.integration_test }} )
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: integ:run
      - name: Archive k8s logs
        if: ${{ always() }}
        # actions/upload-artifact@v1
        uses: actions/upload-artifact@v2
        with:
          name: k8s-logs
          path: ./build/kubectl_dump
