name: Cass Operator Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    # Allow to rerun this for a tag to get updated UBI-images

jobs:
  release_cass_operator:
    name: Release Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        if: ${{ !env.ACT }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Set git parsed values
        if: ${{ !env.ACT }}
        id: vars
        shell: bash
        run: |
          echo ::set-output name=sha_short::$(git rev-parse --short=8 ${{ github.sha }})
          echo ::set-output name=tag_name::${GITHUB_REF#refs/tags/}
          echo "TARGET_VERSION=$(echo ${GITHUB_REF#refs/tags/} | awk '{print substr($0,2)}')" >> $GITHUB_ENV
      # - name: Set git parsed values for act
      #   if: ${{ env.ACT }}
      #   id: vars
      #   shell: bash
      #   run: |
      #     echo ::set-output name=sha_short::$(git rev-parse --short=8 ${{ github.sha }})
      #     echo ::set-output name=tag_name::$(git describe --abbrev=0 --tags)
      #     echo "TARGET_VERSION=$(echo $(git describe --abbrev=0 --tags) | awk '{print substr($0,2)}')" >> $GITHUB_ENV
      - name: Build and push system-logger
        id: docker_build_system-logger
        uses: docker/build-push-action@v2
        with:
          file: logger.Dockerfile
          build-args: |
            VERSION=${{ env.TARGET_VERSION }}
          context: .
          push: ${{ !env.ACT }}
          tags: k8ssandra/system-logger:${{ steps.vars.outputs.tag_name}}
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Build and push cass-operator
        id: docker_build_cass-operator
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          build-args: |
            VERSION=${{ env.TARGET_VERSION }}
          context: .
          push: ${{ !env.ACT }}
          tags: k8ssandra/cass-operator:${{ steps.vars.outputs.tag_name}}
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Create bundle
        run: |
          make IMG=k8ssandra/cass-operator:${{ steps.vars.outputs.tag_name}} VERSION=${{ env.TARGET_VERSION }} bundle
      - name: Build and push cass-operator-bundle
        id: docker_build_cass-operator
        uses: docker/build-push-action@v2
        with:
          file: bundle.Dockerfile
          build-args: |
            VERSION=${{ env.TARGET_VERSION }}
          context: .
          push: ${{ !env.ACT }}
          tags: k8ssandra/cass-operator-bundle:${{ steps.vars.outputs.tag_name}}
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
